CC = gcc
CFLAGS = -O2 -Wall -I .
LIB = -lpthread

all: echoclient echoserver

csapp.o: csapp.c csapp.h 
	$(CC) $(CFLAGS) -c csapp.c

echoclient: echoclient.c csapp.o
	$(CC) $(CFLAGS) -o echoclient echoclient.c csapp.o $(LIB)

echoserver: echoserveri.c csapp.o
	$(CC) $(CFLAGS) -o echoserver echoserveri.c csapp.o $(LIB)
        
clean:
	rm -f *.o echoclient echoserver *~